### ISSUE TITLE
occasional "unexpected ModRevision" errors

### ISSUE THREAD

**Issue by jgraettinger** [gazette/core#202]
We've seen occasional `unexpected ModRevision (it's too small; prev ... ` errors logged in a gazette production cluster which are mysterious. They're noisy but harmless -- the `keyspace` does the right thing of dropping the duplicate event -- however they're also inexplicable.

Code diving, the only way I've found that this can happen is if the etcd `Watch` client sends duplicate events, which it's not supposed to do. One thing I _am_ seeing is that these logs co-occur with the broker switching over to another Etcd node (see how `memberId` changes below), so this may be a bug in `Watch` tickled on recovery & reconnect:

> {"level":"info","memberId":9290711433539710000,"msg":"etcd MemberId/RaftTerm changed","raftTerm":172,"time":"2019-05-08T08:26:36Z","update.MemberId":5603996233891104000,"update.RaftTerm":172}

**Comment by adayNU** [comment]
Is this possibly fixed in 49c4ae6?

**Comment by jgraettinger** [comment]
Duplicate of #248 .
