### ISSUE TITLE
Is Gazette suitable for use as a network filesystem?

### ISSUE THREAD

**Issue by ivanr** [gazette/core#261]
I've been following your work with Gazette and I like it very much. I have a question about something I haven't been quite able to understand from reading and re-reading the documentation. I would appreciate a quick response if you have a moment.

This is what I've been wondering about:

- Could journals be created on the fly, for example from a template on first write?

- Would there be an issue with hundreds and thousands of active journals?

- For real-time processing, can clients subscribe to read what is written to a family of journals (i.e., see all writes to all journals in the same "folder")?

In essence, I am trying to understand if we could use Gazette as a reliable immutable network filesystem. We would have many worker nodes with long-running processes. We'd like those nodes to record their results somewhere for subsequent real-time or batch processing. At some point we may want to iterate through open journals, close them, wait until they're fully persisted, then process them further, archive them to another location, etc.

Many thanks for your thoughts.

**Comment by jgraettinger** [comment]
Thanks. This is from an email thread I asked @ivanr if he'd be willing to put here for posterity.

- Can journals be created on the fly?

Yes, definitely. There isn't a ready example in the core repo itself -- it requires domain knowledge re: how on-the-fly journals should be specified -- but this is a supported pattern I use myself. It requires logic somewhere (perhaps the writer) that compares an intended destination journal with journals that actually exist (eg from a [PolledList](https://godoc.org/go.gazette.dev/core/broker/client#PolledList)), and currently it's on you to handle races in journal creation, etc.

Note it's perfectly fine to issue a write to a journal that doesn't exist using client.AppendService or [gazctl journals append --direct](https://gazette.readthedocs.io/en/latest/reference-gazctl.html#gazctl-journals-append) -- it will complain via logging, but so long as you have something asynchronously create the journal, it will keep retrying until it succeeds.

- Would there be an issue with hundreds, thousands, and more active journals?

Nope. Aside from hardware, the bottlenecks in scaling are coordination through Etcd (with overhead that's linear on journals & members) and the speed with which brokers can re-calculate optimal assignments of journals (technically O(N^3), but most always O(N)). I'd be very confident scaling to 10K, and believe there's headroom to comfortably scale to 100K+ journals with the current implementation. I have ideas on how to go beyond that, too, but frankly it just hasn't come up.

There's a good benchmark for playing with this:
  go test -v -run=XXX -bench=. -benchtime=30s ./allocator 

For example on my laptop it simulates a rolling deployment of 350 brokers managing 35K journals, in 10s of seconds. It runs against a local Etcd server and includes all of that overhead (but not network latency).

- For real-time processing, can clients subscribe to read what is written to a family of journals?

Yes. You can see this in action, today, with the gazctl journals read command. It monitors a label selector and starts reads of matched journals as they're created. It will also do durable offset tracking across invocations, if you ask it.

_FYI I'm closing this issue as it's not actionable, but happy to keep discussing here._

**Comment by ivanr** [comment]
@jgraettinger Many thanks for your quick response.

> > Can journals be created on the fly?
>
> Yes, definitely. There isn't a ready example in the core repo itself -- it requires domain knowledge re: how on-the-fly journals should be specified -- but this is a supported pattern I use myself. It requires logic somewhere (perhaps the writer) that compares an intended destination journal with journals that actually exist (eg from a PolledList), and currently it's on you to handle races in journal creation, etc.

Where would this code go, in the brokers presumably? Does that mean that we'd need to run a fork of Gazette?

**Comment by jgraettinger** [comment]
No; by _the writer_ I meant your client application that's doing the appending. And in your shoes, I'd see how far I could get just using `gazctl` before jumping into writing _anything_.

* If you have any kind of registration flow in your application that implies a new journal and can be hooked into, I'd generate the YAML spec then and feed to `gazctl journals apply`.
* `gazctl journals append --mapping=direct` takes alternating lines of "journal-name\nmessage\n", for dynamic routing of appends.
* You could even use `tee` to have another process watch those journals and look for new ones to create, issuing `gazctl journals apply` as needed.
