### ISSUE TITLE
allow `protocol.Journal` to represent query components for client-managed context

### ISSUE THREAD

**Issue by jgraettinger** [gazette/core#279]
**Motivation**: `protocol.Journal`, `protocol.Offset`, and `protocol.Offsets` (defined as `map[Journal]Offset`) are pervasive types throughout the Gazette ecosystem. `message` sequencing semantics and the `consumers` framework rely on them heavily (especially the `Offsets` map), to understand processing progress and checkpoints.

An unfortunate constraint that's arisen is this means that a consumer shard may read a journal only once. As an example of why that's unfortunate, consider an (unimplemented) read delay feature, which would allow one to specify that a journal should be read with i.e. a 20 minute delay with respect to it's UUID clock.

Suppose I want to group / session-ize a sequence of events. I could accomplish this by having two separate reads of a single journal within a shard:
 * Read "type=index" proceeds in real-time, and indexes a windows of events per-user within the shard's Store.
 * Read "type=emit" proceeds with a N-minute delay, fetches the indexed window of events from the store, emits them, and clears the window within the Store.

**Proposal**: We would update the semantics of `protocol.Journal` such that it can also represent a contextual _suffix_ which is meaningful to the client, and which the broker knows to drop when mapping to an actual identified journal. **_This is spiritually similar to, and modeled after, the "query" component of a URL._**

Currently, `protocol.Journal` is precisely a journal name. It's validated to be a `path/like/component`, with a [very restricted allowed character set](https://github.com/gazette/core/blob/fe5e6d7dde574b3ef998cddac05ac3173588035d/broker/protocol/validator.go#L71) for non-alphanumeric characters.

We would relax `protocol.Journal` to allow for an optional `?suffix`, as in `some/journal?index` or `some/journal?foo=emit&bar=baz` (note that `?` and `&` are not currently allowed characters in a `protocol.Journal`, though `=` is).

Any place that a Journal is used, such as a consumer `ShardSpec`, would be able to use this notation. Notably, this would allow a `ShardSpec` to include a journal multiple times as a `Source`, so long as each is identified by a different suffix. Offset tracking and consumer checkpoints would continue to work as expected, with each suffix being separately tracked.

As with URLs, `?suffix` portions of a journal would be sent to brokers as part of `ReadRequest`'s, etc. The broker would drop the suffix at the last mile, immediately before attempting to resolve to a specific journal resource. This is expected to make request disambiguation, debugging, and tracing easier since read contexts will be naturally surfaced in logs / gRPC traces.

`?suffix` extensions would *not* be allowed in `JournalSpecs` themselves. They cannot be part of a Journal's actual name, and as such will never produce a fragment file which includes a `?suffix` in the path.

The HTTP Gateway already presents a REST API by which Journals may be accessed, which makes use of query components (eg, `?block=true`). Currently, the gateway rejects request which provide query components which
it doesn't explicitly know about & handle. The behavior of the gateway would be changed to pipe through _all_ query components within a journal suffix, in the proxied gRPC requests it generates as part of it's natural request handling.

**Backward Compatibility**: This proposal is fully compatible with existing deployments of Gazette consumers, their stores, and legacy clients, since the protocol itself will not change and a currently-valid `protocol.Journal` value will remain valid, with its existing semantics.

An updated client or consumer application _which makes use of_ `?suffix`'s must wait until brokers have been updated to understand and appropriately handle `?suffix`'s.

**Alternatives Considered**: A core motivation for this proposal is the need to represent a _multi-map_ of journals within a consumer shard processing context. This has broad implications in message sequencing, consumer checkpointing, and other areas. If we were _not_ to change `protocol.Journal` semantics such that it is capable of directly representing a multi-map, then some other organizing concept must be introduced which allows for naming specific reads and the processing context under which they're undertaken -- i.e., a type capturing the tuple ("some/journal", "index") vs ("some/journal", "emit"). Pragmatically, this would be a very large change to the consumers framework (whereas this proposal appears straightforward).

Introducing such a type would add significant new cognitive complexity (eg, now I must consider this type even if I otherwise don't need to distinguish or represent a processing context), and far more importantly, would be very likely to break backward compatibility.

This proposal is believed motivated over this alternative by:
 * The widespread use and familiarity with `?query-components` in the HTTP world, and the closely-related semantics in their usage here.
 * Their existing (limited) usage within the HTTP Gateway
 * The ability to easily maintain full backward compatibility with this change, while still accomplishing the key objective.

**Comment by psFried** [comment]
I'd like to talk through what this particular use case might look like if we had to implement it under the current restriction (_without_ this feature). Please correct if any of this isn't right. The use case is that we want one piece of (stateful) processing code to process two separate reads from a single Journal.

Without this feature, you'd need to have two separate Consumer deployments, one for each read. You'd then have to factor out your common processing code to either be a network service, or to at least use some other network service to manage its state. This would mean going from a single deployment in the case of a single read, to 3 deployments in the case of 2 reads, which represents a pretty significant jump in architectural complexity.

Apart from that, the current restriction of one read per journal seems a bit incongruous  with the existing capability of a single consumer to read from multiple _different_ Journals. We're basically saying that multiple reads are fine, except for the caveat that they have to all be from different Journals. If we implement this, then we would basically just say that multiple reads are fine, and you use a query component to disambiguate them.

If that all sounds right, then I'd definitely be in favor of implementing this.

**Comment by jgraettinger** [comment]
Yep, that's basically all correct. For the sessionization example above (and assuming that a read delay feature exists), given current limitations you _cannot_ have one shard both index and (later) emit records from the same journal, and you'd have to do this as two separate consumer shards which communicate through a shard external state, as you note.

**Comment by jgraettinger** [comment]
Done.
